# Generated by Django 6.0.3 on 2026-03-15 15:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=32, unique=True, verbose_name="Номер"
                    ),
                ),
                (
                    "inventory_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата инвентаризации",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("partial", "Частичная"), ("full", "Полная")],
                        default="partial",
                        max_length=10,
                        verbose_name="Охват",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("posted", "Проведен")],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата проведения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвентаризация",
                "verbose_name_plural": "Инвентаризации",
                "ordering": ["-inventory_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Артикул"
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="Наименование")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатура",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Наименование")),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Наименование")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=32, unique=True, verbose_name="Номер"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Приход"),
                            ("issue", "Расход"),
                            ("adjustment", "Корректировка"),
                        ],
                        default="receipt",
                        max_length=20,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "operation_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата документа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("posted", "Проведен")],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата проведения"
                    ),
                ),
                (
                    "source_inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to="warehouse_app.inventorydocument",
                        verbose_name="Источник инвентаризации",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="warehouse_app.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ движения",
                "verbose_name_plural": "Документы движения",
                "ordering": ["-operation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="Количество"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="warehouse_app.stockdocument",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_lines",
                        to="warehouse_app.item",
                        verbose_name="Номенклатура",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка документа",
                "verbose_name_plural": "Строки документов",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="warehouse_app.unit",
                verbose_name="Ед. изм.",
            ),
        ),
        migrations.AddField(
            model_name="inventorydocument",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_documents",
                to="warehouse_app.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.CreateModel(
            name="InventoryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Учетное количество",
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        verbose_name="Фактическое количество",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="warehouse_app.inventorydocument",
                        verbose_name="Инвентаризация",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_lines",
                        to="warehouse_app.item",
                        verbose_name="Номенклатура",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка инвентаризации",
                "verbose_name_plural": "Строки инвентаризации",
                "ordering": ["id"],
                "unique_together": {("inventory", "item")},
            },
        ),
    ]
