# Generated by Django 6.0.3 on 2026-03-15 19:37

import django.core.validators
from django.db import migrations, models


def set_default_display_precision(apps, schema_editor):
    Unit = apps.get_model("warehouse_app", "Unit")
    Unit.objects.filter(code__iexact="pcs").update(display_precision=0)


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="display_precision",
            field=models.PositiveSmallIntegerField(
                default=3,
                validators=[django.core.validators.MaxValueValidator(6)],
                verbose_name="Знаков после запятой",
            ),
        ),
        migrations.RunPython(set_default_display_precision, migrations.RunPython.noop),
    ]
