# Generated by Django 6.0.3 on 2026-04-10 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0002_unit_display_precision"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryline",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="stockdocument",
            name="destination_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_documents",
                to="warehouse_app.warehouse",
                verbose_name="Склад-получатель",
            ),
        ),
        migrations.AlterField(
            model_name="stockdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("receipt", "Приход"),
                    ("issue", "Расход"),
                    ("adjustment", "Корректировка"),
                    ("transfer", "Перемещение"),
                ],
                default="receipt",
                max_length=20,
                verbose_name="Тип документа",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryline",
            constraint=models.UniqueConstraint(
                fields=("inventory", "item"), name="uniq_inventory_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockdocumentline",
            constraint=models.UniqueConstraint(
                fields=("document", "item"), name="uniq_stock_document_item"
            ),
        ),
    ]
