# Generated by Django 6.0.3 on 2026-06-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0003_alter_inventoryline_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("stock_document_posted", "Документ проведен"),
                            ("inventory_posted", "Инвентаризация проведена"),
                            (
                                "inventory_adjustment_created",
                                "Автокорректировка создана",
                            ),
                        ],
                        max_length=40,
                        verbose_name="Тип события",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="Событие")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "inventory_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to="warehouse_app.inventorydocument",
                        verbose_name="Инвентаризация",
                    ),
                ),
                (
                    "stock_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to="warehouse_app.stockdocument",
                        verbose_name="Документ движения",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_events",
                        to="warehouse_app.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие активности",
                "verbose_name_plural": "События активности",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
