# Generated by Django 6.0.3 on 2026-06-05 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0006_itemcategory_item_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("documents", "Документы движения"),
                            ("balances", "Текущие остатки"),
                        ],
                        max_length=20,
                        verbose_name="Раздел",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Название")),
                ("query_params", models.JSONField(verbose_name="Параметры")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="По умолчанию"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохраненное представление",
                "verbose_name_plural": "Сохраненные представления",
                "ordering": ["scope", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "scope", "name"),
                        name="unique_saved_view_name_per_user_scope",
                    )
                ],
            },
        ),
    ]
