# Generated by Django 6.0.3 on 2026-06-10 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0007_usersavedview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "Ручная"),
                            ("pre_migration", "Перед миграцией"),
                            ("pre_restore", "Перед восстановлением"),
                        ],
                        max_length=32,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("failed", "Ошибка"),
                            ("restored", "Восстановлена"),
                        ],
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "backup_path",
                    models.CharField(max_length=500, verbose_name="Путь к копии"),
                ),
                (
                    "source_database_path",
                    models.CharField(max_length=500, verbose_name="Путь к базе"),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Размер, байт"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="SHA-256"),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Версия приложения"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Сообщение"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резервная копия",
                "verbose_name_plural": "Резервные копии",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
