# Generated by Django 6.0.3 on 2026-06-10 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse_app",
            "0009_activityevent_actor_activityevent_actor_label_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("stock_document_posted", "Документ проведен"),
                    ("inventory_posted", "Инвентаризация проведена"),
                    ("inventory_adjustment_created", "Автокорректировка создана"),
                    ("item_import_committed", "Импорт номенклатуры выполнен"),
                    (
                        "opening_inventory_import_committed",
                        "Импорт стартовых остатков выполнен",
                    ),
                    ("manual_backup_created", "Резервная копия создана"),
                    ("demo_data_reset", "Демо-данные перезагружены"),
                    ("reference_record_changed", "Справочник изменен"),
                ],
                max_length=40,
                verbose_name="Тип события",
            ),
        ),
        migrations.AlterField(
            model_name="activityevent",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_events",
                to="warehouse_app.warehouse",
                verbose_name="Склад",
            ),
        ),
    ]
